-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 15:06:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proveedores` (
  `idProv` INT NOT NULL AUTO_INCREMENT,
  `nombreProv` VARCHAR(45) NOT NULL,
  `naciProv` DATE NOT NULL,
  `correoProv` VARCHAR(45) NOT NULL,
  `claveProv` VARCHAR(45) NOT NULL,
  `cedulaProv` INT NOT NULL,
  PRIMARY KEY (`idProv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clientes` (
  `idCli` INT NOT NULL AUTO_INCREMENT,
  `nombreCli` VARCHAR(45) NOT NULL,
  `naciCli` VARCHAR(45) NULL,
  `correoCli` VARCHAR(45) NULL,
  `claveCli` VARCHAR(45) NULL,
  `cedulaCli` VARCHAR(45) NULL,
  PRIMARY KEY (`idCli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ciudades` (
  `idCiudades` INT NOT NULL AUTO_INCREMENT,
  `NombreCiu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCiudades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lugares` (
  `idLug` INT NOT NULL AUTO_INCREMENT,
  `capacidadLug` INT NOT NULL,
  `direccionLug` VARCHAR(45) NOT NULL,
  `nombreLug` VARCHAR(45) NOT NULL,
  `Ciudades_idCiudades` INT NOT NULL,
  PRIMARY KEY (`idLug`, `Ciudades_idCiudades`),
  INDEX `fk_Lugares_Ciudades1_idx` (`Ciudades_idCiudades` ASC),
  CONSTRAINT `fk_Lugares_Ciudades1`
    FOREIGN KEY (`Ciudades_idCiudades`)
    REFERENCES `Ciudades` (`idCiudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eventos` (
  `idEve` INT NOT NULL AUTO_INCREMENT,
  `nombreEve` VARCHAR(45) NOT NULL,
  `fechIniEve` DATE NOT NULL,
  `fechFinEve` DATE NOT NULL,
  `precioEve` INT NOT NULL,
  `Lugares_idLug` INT NOT NULL,
  PRIMARY KEY (`idEve`, `Lugares_idLug`),
  INDEX `fk_Eventos_Lugares1_idx` (`Lugares_idLug` ASC),
  CONSTRAINT `fk_Eventos_Lugares1`
    FOREIGN KEY (`Lugares_idLug`)
    REFERENCES `Lugares` (`idLug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TipoBoleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoBoleta` (
  `idTB` INT NOT NULL AUTO_INCREMENT,
  `nombreTB` VARCHAR(45) NOT NULL,
  `porcentajeTB` VARCHAR(45) NOT NULL,
  `Proveedores_idProv` INT NOT NULL,
  PRIMARY KEY (`idTB`, `Proveedores_idProv`),
  INDEX `fk_TipoBoleta_Proveedores_idx` (`Proveedores_idProv` ASC),
  CONSTRAINT `fk_TipoBoleta_Proveedores`
    FOREIGN KEY (`Proveedores_idProv`)
    REFERENCES `Proveedores` (`idProv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DetalleEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DetalleEvento` (
  `idProv` INT NOT NULL,
  `idEve` INT NOT NULL,
  `idTB` INT NOT NULL,
  `cantidadDE` INT NOT NULL,
  PRIMARY KEY (`idProv`, `idEve`, `idTB`),
  INDEX `fk_DetalleEvento_Eventos1_idx` (`idEve` ASC),
  INDEX `fk_DetalleEvento_TipoBoleta1_idx` (`idTB` ASC),
  CONSTRAINT `fk_DetalleEvento_Proveedores1`
    FOREIGN KEY (`idProv`)
    REFERENCES `Proveedores` (`idProv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleEvento_Eventos1`
    FOREIGN KEY (`idEve`)
    REFERENCES `Eventos` (`idEve`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleEvento_TipoBoleta1`
    FOREIGN KEY (`idTB`)
    REFERENCES `TipoBoleta` (`idTB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FacturaVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FacturaVenta` (
  `idFacturaVenta` INT NOT NULL AUTO_INCREMENT,
  `fechaFV` DATE NOT NULL,
  `horaFV` VARCHAR(45) NOT NULL,
  `idEve` INT NOT NULL,
  `idCli` INT NOT NULL,
  PRIMARY KEY (`idFacturaVenta`),
  INDEX `fk_FacturaVenta_Eventos1_idx` (`idEve` ASC),
  INDEX `fk_FacturaVenta_Clientes1_idx` (`idCli` ASC),
  CONSTRAINT `fk_FacturaVenta_Eventos1`
    FOREIGN KEY (`idEve`)
    REFERENCES `Eventos` (`idEve`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacturaVenta_Clientes1`
    FOREIGN KEY (`idCli`)
    REFERENCES `Clientes` (`idCli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DetalleFacturaVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DetalleFacturaVenta` (
  `idFacturaVenta` INT NOT NULL,
  `idTB` INT NOT NULL,
  `cantidadDFV` INT NOT NULL,
  PRIMARY KEY (`idFacturaVenta`, `idTB`),
  INDEX `fk_DetalleFacturaVenta_TipoBoleta1_idx` (`idTB` ASC),
  CONSTRAINT `fk_DetalleFacturaVenta_FacturaVenta1`
    FOREIGN KEY (`idFacturaVenta`)
    REFERENCES `FacturaVenta` (`idFacturaVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleFacturaVenta_TipoBoleta1`
    FOREIGN KEY (`idTB`)
    REFERENCES `TipoBoleta` (`idTB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritoCompra` (
  `idCC` INT NOT NULL AUTO_INCREMENT,
  `Clientes_idCli` INT NOT NULL,
  `TipoBoleta_idTB` INT NOT NULL,
  `idEve` INT NOT NULL,
  PRIMARY KEY (`idCC`, `Clientes_idCli`, `TipoBoleta_idTB`, `idEve`),
  INDEX `fk_CarritoCompra_Clientes1_idx` (`Clientes_idCli` ASC),
  INDEX `fk_CarritoCompra_TipoBoleta1_idx` (`TipoBoleta_idTB` ASC),
  INDEX `fk_CarritoCompra_Eventos1_idx` (`idEve` ASC),
  CONSTRAINT `fk_CarritoCompra_Clientes1`
    FOREIGN KEY (`Clientes_idCli`)
    REFERENCES `Clientes` (`idCli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarritoCompra_TipoBoleta1`
    FOREIGN KEY (`TipoBoleta_idTB`)
    REFERENCES `TipoBoleta` (`idTB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarritoCompra_Eventos1`
    FOREIGN KEY (`idEve`)
    REFERENCES `Eventos` (`idEve`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administradores` (
  `idAdministradores` INT NOT NULL,
  `nombreAdm` VARCHAR(45) NOT NULL,
  `naciAdm` VARCHAR(45) NOT NULL,
  `correoAdm` VARCHAR(45) NOT NULL,
  `claveAdm` VARCHAR(45) NOT NULL,
  `cedulaAdm` INT NOT NULL,
  PRIMARY KEY (`idAdministradores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ActLug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActLug` (
  `idAL` INT NOT NULL AUTO_INCREMENT,
  `dAdministradores` INT NOT NULL,
  `idLug` INT NOT NULL,
  `fechaAL` DATE NOT NULL,
  INDEX `fk_ActLug_Lugares1_idx` (`idLug` ASC),
  PRIMARY KEY (`idAL`),
  CONSTRAINT `fk_ActLug_Administradores1`
    FOREIGN KEY (`dAdministradores`)
    REFERENCES `Administradores` (`idAdministradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActLug_Lugares1`
    FOREIGN KEY (`idLug`)
    REFERENCES `Lugares` (`idLug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ActCiu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActCiu` (
  `idAC` INT NOT NULL AUTO_INCREMENT,
  `idAdministradores` INT NOT NULL,
  `idCiudades` INT NOT NULL,
  `fechaAC` DATE NOT NULL,
  INDEX `fk_ActCiu_Ciudades1_idx` (`idCiudades` ASC),
  PRIMARY KEY (`idAC`),
  CONSTRAINT `fk_ActCiu_Administradores1`
    FOREIGN KEY (`idAdministradores`)
    REFERENCES `Administradores` (`idAdministradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActCiu_Ciudades1`
    FOREIGN KEY (`idCiudades`)
    REFERENCES `Ciudades` (`idCiudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
